### ISSUE TITLE
Find the sum of all the multiples of  3 or 5 below N.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#101]
**Details** 
Programming language : Any
Directory : Algorithms/Mathematical Algorithms
Explanation : Optional
Time complexity : O(1)

**Comment by williamgherman** [comment]
Hi there! I'll get working on it.

**Comment by DanielJoseph98** [comment]
Going to start in c++!

**Comment by MattNot** [comment]
Working on it in Javascript!

**Comment by goore3** [comment]
Working on it in python

**Comment by Robcross** [comment]
#115 
`#include<bits/stdc++.h>
using namespace std;
int main()
{
    int n,three,five,fifteen;
    cin>>n;
    n=n-1;
    three=n/3;
    five=n/5;
    fifteen=n/15;
    long long int ans;
    ans=(3*(three*(three+1)/2))+(5*(five*(five+1)/2))-(15*(fifteen*(fifteen+1)/2));
    cout<<ans<<endl;
    return 0;
}
`

**Comment by Robcross** [comment]
#121
