### ISSUE TITLE
Implement insertion sort in any language

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#11]
Add it to the algorithms folder.

**Comment by Shaurya62000** [comment]
` 
#include<iostream>
int main()
{
   int i, key, j,arr[40],n;
   cin>>n;
   for(i=0;i<n;i++)
       cin>>arr[i];
   for (i = 1; i < n; i++)
   {
       key = arr[i];
       j = i-1;
       while (j >= 0 && arr[j] > key)
       {
           arr[j+1] = arr[j];
           j = j-1;
       }
       arr[j+1] = key;
   }
}`
