### ISSUE TITLE
Sum of keys of all the cousins of a node in a binary tree.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#111]
Cousins of a node in a binary tree are those nodes, which are at the same level (same distance from the root) and don't have the same parent as that of the given node (siblings are not cousins :-) ). Given a binary tree and the key of a node, find the sum of keys of all the cousins of the tree. The keys of the nodes are distinct.
**Details :**
Programming language : C, C++, Java, Python
Explanation : Yes
Directory : Data Structures/ Trees

**Comment by krp12345** [comment]
I can do this. going to implement in all languages.

**Comment by krp12345** [comment]
Done in PR.
