### ISSUE TITLE
Create a Doubly linked list

### ISSUE THREAD

**Issue by Pushkar03** [rathoresrikant/HacktoberFestContribute#1254]
I would like to create a doubly linked list with all its operation including insertion,deletion and display of the elements of the list.

**Comment by Ayan-Sharma-aks** [comment]
Hi Pushkar, I would like to resolve this issue. Please assign it to me in order to do the needful.

**Comment by janvichoudhary08** [comment]
hey please  assign me  this issue as a part of  hacktoberfest.
