### ISSUE TITLE
Print all the perfect numbers in a given range.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#184]
Given a range of numbers (L to R) , print all the [perfect numbers ](https://en.wikipedia.org/wiki/Perfect_number) within L and R (inclusive) in any language.
Directory : Algorithms/Mathematical Algorithms

**Comment by kalpesh30** [comment]
I would like to work on this issue. Can I do?

**Comment by nirupamgunwal** [comment]
I would be working on it in Python. Can i work on it @rathoresrikant ?
