### ISSUE TITLE
Find the first non-repeating character in a string.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#266]
Programming language : Any

**Comment by SarveshBajaj** [comment]
Is it still open to work upon?
I would like to have a go at it

**Comment by rathoresrikant** [comment]
Check if someone has already added the code in the same language as yours. If not, you are good to go.

**Comment by SarveshBajaj** [comment]
> Check if someone has already added the code in the same language as yours. If not, you are good to go.

Thanks

**Comment by SarveshBajaj** [comment]
Here is my pull request:
[https://github.com/rathoresrikant/HacktoberFestContribute/pull/373/](url)

**Comment by SarveshBajaj** [comment]
Pull request:
https://github.com/rathoresrikant/HacktoberFestContribute/pull/373/
