### ISSUE TITLE
Given a string, remove all vowels from it.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#282]

**Comment by arjbholu** [comment]
#305

**Comment by SarveshBajaj** [comment]
Is this issue still open?
If yes, Can I work on it?

**Comment by charubansal12** [comment]
@rathoresrikant  I have created a PR for this issue in cpp, can you review it? https://github.com/rathoresrikant/HacktoberFestContribute/pull/332
