### ISSUE TITLE
Remove extra spaces from a string.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#313]
Given a string that contains many extra spaces between two words. Remove the consecutive space such that there two words are separated by a single white space.
Programming language : Any

**Comment by sharad-sharma** [comment]
can i work on it

**Comment by HemantKhatri004** [comment]
This code replaces a consecutive set of whitespace characters (\s+) by a single white space. Note that a white-space character also includes tab and newlines. Replace \s by a space if you only want to replace spaces.

var string = "    This    should  become   something          else   too . ";
string = string.replace(/\s+/g, " ");
