### ISSUE TITLE
Implementation of Trie data structure

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#32]
Details 
Programming Languages : C, C++
Directory : Data Structures / Trie
Explanation : Optional

**Comment by yash04g** [comment]
#include<iostream>
#include<string>
using namespace std;
class TrieNode{
public:
	char data;
	TrieNode **children;
	bool isTerminal;
	TrieNode(char data){
		this->data = data;
		children = new TrieNode*[26]; // 26 represents that all the letters are in lower case 
		for(int i=0;i<26;i++){
			children[i] = NULL;
		}
		isTerminal = false;
	}

};
class Trie{
	TrieNode *root;
public:
	Trie(){
		root = new TrieNode('/0');
	}
	void insertWord(TrieNode *root, string word){
		if(word.size()==0){
			root->isTerminal = true;
		}
		int index = word[0] - 'a';
		TrieNode *child;
		if(root->children[index]!=NULL){
			child = root->children[index];
		}
		else{
			child = new TrieNode(word[0]);
			root->children[index] = child;
		}
		insertWord(root,word.substr(1));
	}
	void InsertWord(string word){
		insertWord(root,word);
	}
	bool search(TrieNode *root,string word){
		if(word.size()==0){
			return root->isTerminal;
		}
		int index = word[0] - 'a';
      	TrieNode *child;
		if(root->children[index]!=NULL){
			child = root->children[index];	
		}
		else{
			return false;
		}
      	return search(child,word.substr(1));
	}
  	bool search(string word){
      return search(root,word);
    }
};

**Comment by shubhamguptaji** [comment]
Can I?
