### ISSUE TITLE
Swap two numbers without using a temporary variable.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#456]
Programming language : Any

**Comment by sagarkansal** [comment]
I would like to contribute to it. #456

**Comment by pariola** [comment]
can one still add using another language???

**Comment by sagarkansal** [comment]
Actually i didn't get what you are trying to say.

**Comment by bicmfcs** [comment]
see #469

**Comment by pariola** [comment]
@sagarkansal I was asking if one is allowed to add the same solution in another language!

**Comment by sagarkansal** [comment]
Yes, it can be done in any language.

**Comment by sagarkansal** [comment]
Yes everyone is allowed to any changes.

**Comment by cheevu-RS** [comment]
will write cpp code
