### ISSUE TITLE
Find the number of times an element occurs in a sorted array.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#483]

**Comment by WebDevRaj** [comment]
I'll do this in java

**Comment by DeepanshAgrawal** [comment]
Done in C++.
Have a Look.
https://github.com/DeepanshAgrawal/HacktoberFestContribute/blob/master/Algorithms/Array/count%20occurence.cpp

**Comment by YASHYK47** [comment]
Done in c
