### ISSUE TITLE
Detecting a loop in a linked list

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#56]
Details 
Programming languages : C, C++, Java, Python
Explanation : Yes
Directory : Data Structures
Please refrain from using plagiarised code. Happy coding !

**Comment by LeCeee** [comment]
On it.

**Comment by ikad95** [comment]
Can I take this?

**Comment by Pranay10rawat** [comment]
resolved in c++ with explanation
