### ISSUE TITLE
Move the last element to the front of a given linked list.

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#587]
Programming language : Any
Directory : Data Structures/Linked Lists

**Comment by Rajat-dey** [comment]
Working on this project..

**Comment by Rajat-dey** [comment]
The code is added in the respective Directory.

**Comment by ccampean** [comment]
For some season the [
f4b9541 ](https://github.com/rathoresrikant/HacktoberFestContribute/pull/709/commits/f4b95414090824b701841ed394bb89a201f1ea8c) commit entered on the [709](https://github.com/rathoresrikant/HacktoberFestContribute/pull/709) PR but I wanted to be a separate pull request
