### ISSUE TITLE
Implement RSA algorithm

### ISSUE THREAD

**Issue by rathoresrikant** [rathoresrikant/HacktoberFestContribute#92]
RSA is an algorithm used by modern computers to encrypt and decrypt messages. It is an asymmetric cryptographic algorithm. (Wikipedia)

**Details**
Programming language : C, C++, Java, Python
Directory : Algorithms
Explanation : Yes

Please comment here to claim the issue. (language specific)
To know more about RSA proceed [here](https://brilliant.org/wiki/rsa-encryption/) .

**Comment by aakash18012** [comment]
i will take this.

**Comment by sachincool** [comment]
I'll do this in python

**Comment by Reisande** [comment]
If no one takes this for C++, I can do it.

**Comment by caiodangelo** [comment]
Taking the Java version

**Comment by jscd** [comment]
I'll do the C one.

**Comment by Reisande** [comment]
check
